### ISSUE TITLE
in dataset, there is no train_scenes.txt (or any splited set's text files)

### ISSUE THREAD

**Issue by HyunsuYEE** [Mercerai/EvGGS#3]
```
(evggs) root@d1b187c3ab58:~/dev/EvGGS# python train_gs.py 
configs/Ev3D_pretrain.yaml
EXP NAME:  experimental_name
Traceback (most recent call last):
  File "train_gs.py", line 233, in <module>
    trainer = Trainer()
  File "train_gs.py", line 27, in __init__
    batch_size=1, shuffle=False)
  File "/root/dev/EvGGS/lib/dataset/Ev3D.py", line 83, in __init__
    dataset = concatenate_datasets_split(base_folders, ReadEventFromH5, split=split)
  File "/root/dev/EvGGS/lib/dataset/Ev3D.py", line 68, in concatenate_datasets_split
    with open(scenes_path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/train_scenes.txt'
```

this part is in the **def concatenate_datasets_split(base_folders, dataset_type, split, dataset_kwargs={})** function
I download synthetic & real dataset both, but there is no txt files anywhere.
can you notice about it?
thank you.

**Comment by Mercerai** [comment]
Thanks for sharing this bug with us. Today we have fixed the synthetic zip file, please download it again. The training.txt of real data would be fixed tomorrow.

**Comment by HyunsuYEE** [comment]
thank you. thanks to your modification, I could run the train_gs.py. but, I want to know how to visualize the img or depth or masks like your pipe.
can you inform about how to visualize the depth or masks (I request the code!)?
![image](https://github.com/user-attachments/assets/b8ee4d95-e292-4490-a7cc-eb9cb88a609b)
But, I want below depth map visualization.
<img width="896" alt="image" src="https://github.com/user-attachments/assets/f6dc6187-6ac1-4300-be95-4021d35d1233">

Upper one is visualization which I made. But I think, it is some kind of 'coarse' gt depth.(there is no light and shade in the g.t. depth map.) Can you share your code for visualizing 'dense' depth map?(into the png file)
Thanks for your efforts, I can learn more. :) thank you.

**Comment by Mercerai** [comment]
Thanks for your issue. Of course, this is very easy to convert the depth map into a colored image. You can directly use the function "depth2img(depth)" in the "lib.utils" module. Just directly input the depth into the function, this will smoothly map the depth value by our predefined functional color bar.
